### ISSUE TITLE
The facts items in the sources menu will increase each time you start MITRE CALDERA

### ISSUE THREAD

**Issue by shiracamus** [mitre/emu#4]
The emu plugin recreates the sources facts yaml files with a new UUID every time MITRE CALDERA is started, so it is added  as a new sources facts.  
Something needs to be done.

![increase_facts](https://user-images.githubusercontent.com/4151943/105813788-b7300000-5ff3-11eb-8f29-ac3fb66af067.png)

**Comment by wbooth** [comment]
Thanks I'll update
